env:
  global:
    - CC_TEST_REPORTER_ID=f0de60bb4e95d490f54260360a86ed99776ada3da8570aaae0e90b58ac04783a

language: ruby

rvm:
  - 2.4

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - bundle install; rspec spec --format documentation

after_script:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
